name: Sukant Kumar
parameter_dict:
  n_estimators: [10, 20, 30]
  max_depth: [2,5,8]
  no_components: [30, 50, 80]

IMAGE_DATA_FILE: train.csv.zip
TEST_DATA_FILE: test.csv.zip
LOG_FILENAME: ml_deploy.log
LOGGER_NAME: ml_deploy_log

#MLFLOW EXP DETAILS
EXPERIMENT_NAME: random_forest_pca_1

#Validation Test set Size
TRAIN_VALID_SPLIT_RATIO: 0.2
MAINTAIN_CLASS_BALANCE: True
EVALUATION_SCORE: f1_score_validation