name: Sukant Kumar
parameter_dict:
  n_estimators: [20,40,50]
  max_depth: [2,5,8]
  no_components: [50,80,100]

IMAGE_DATA_FILE: train.csv.zip
TEST_DATA_FILE: test.csv.zip
LOG_FILENAME: ml_deploy.log
LOGGER_NAME: ml_deploy_log

#Pixel Scale Constant
MAX_PIXEL_VALUE: 255

#MLFLOW EXP DETAILS
EXPERIMENT_NAME: random_forest_pca_3

#Validation Test set Size
TRAIN_VALID_SPLIT_RATIO: 0.2
MAINTAIN_CLASS_BALANCE: True
EVALUATION_SCORE: f1_score_validation

#MLFLOW RUNID
MLFLOW_RUN_ID: af5a0d90b7d74481b113c3699773ab03
RF_MODEL_NAME: best_random_forest_model
PCA_DECOMPOSER: pca_decomposer